---
- name: install mysql rpm
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mysql-devel
   - libselinux-python
   - libsemanage-python

- name: Install mysql-python
  shell: easy_install http://sourceforge.net/projects/mysql-python/files/mysql-python/1.2.3/MySQL-python-1.2.3.tar.gz/download

# - name: Configure SELinux to start mysql on any port
#   seboolean: name=mysql_connect_any state=true persistent=yes
#   when: ansible_selinux.status == "enabled"

# - name: Create Mysql configuration file
#   template: src=my.cnf.j2 dest=/etc/my.cnf
#   notify:
#   - restart mysql

# - name: Start Mysql Service
#   service: name=mysqld state=started enabled=yes
