---
- name: install mysql rpm
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mysql-devel
   - libselinux-python
   - libsemanage-python

- name: install mysql python module (via yum)
  when: not ansible_distribution == 'Amazon'
  yum:
    name:  MySQL-python
    state: present

- name: install mysql python module (from source)
  when: ansible_distribution == 'Amazon' # Amazon Linux AMI
  command: 'bash -lc "{{ item }}"'
  with_items:
    - 'cd /usr/tmp && wget http://download.sourceforge.net/sourceforge/mysql-python/MySQL-python-1.2.3.tar.gz'
    - 'cd /usr/tmp && tar xvzf /usr/tmp/MySQL-python-1.2.3.tar.gz'
    - 'cd /usr/tmp/MySQL-python-1.2.3 && python setup.py build'
    - 'cd /usr/tmp/MySQL-python-1.2.3 && python setup.py install'
    - 'rm -rf /usr/tmp/MySQL-python*'

# - name: Configure SELinux to start mysql on any port
#   seboolean: name=mysql_connect_any state=true persistent=yes
#   when: ansible_selinux.status == "enabled"

# - name: Create Mysql configuration file
#   template: src=my.cnf.j2 dest=/etc/my.cnf
#   notify:
#   - restart mysql

# - name: Start Mysql Service
#   service: name=mysqld state=started enabled=yes
